### ISSUE TITLE
Add support kotlin-dsl : build.gradle.kts

### ISSUE THREAD

**Issue by jmfayard** [dougborg/gdub#26]
Gradle scripts can now be written in kotlin, which provides better IDE support

Reproducing steps

```bash
git clone https://github.com/gradle/kotlin-dsl
cd kotlin-dsl/samples/hello-kotlin
$ gw hello
Unable to find a gradle build file named build.gradle
```

=> the script should also be looking for file `build.gradle.kts`

**Comment by dougborg** [comment]
This was released in 0.2.0: https://github.com/dougborg/gdub/releases/tag/v0.2.0
