### ISSUE TITLE
Create a new release

### ISSUE THREAD

**Issue by sudosaket** [dougborg/gdub#30]
The releases page has version 0.1.0 which dates back to 2014. A lot of commits since then including the support for Kotlin DSL.

A new release should be made, and corresponding installation methods should be updated.

For instance, using `brew install gdub` is outdated right now, current workaround is to install from source.

**Comment by audi-trip** [comment]
@dougborg Wondering if there's any plan to follow up on this? It would be great to get the new version of gdub in to brew

**Comment by dougborg** [comment]
This is done! [0.2.0 was released ](https://github.com/dougborg/gdub/releases/tag/v0.2.0)and @tokou updated the brew formula as well! Thanks @tokou!
