### ISSUE TITLE
Add support for downloading wrapper jar

### ISSUE THREAD

**Issue by jvz** [dougborg/gdub#31]
This is more so an issue with how Apache projects typically use Gradle. In typical non-ASF usage, a project using the Gradle wrapper will include the `gradle/wrapper/gradle-wrapper.jar` binary for bootstrapping. However, Apache projects are typically not allowed to distribute binary files in their source releases, so this jar will be excluded in those artifacts. Thus, when I run `gw` in those source directories, I'll get an error message like this:

```
Using gradle at '.../gradlew' to run buildfile '.../build.gradle':

Error: Could not find or load main class org.gradle.wrapper.GradleWrapperMain
```

Thus, my request is: can `gw` be enhanced to download the configured gradle wrapper in `gradle-wrapper.properties`? Or is there a more straightforward way to do this that I hadn't considered like running `gradle wrapper` with whatever system version of Gradle I may have available?

**Comment by vlsi** [comment]
@jvz , I guess it is Gradle's issue rather than gdub's one.

See https://discuss.gradle.org/t/adding-gradle-wrapper-files-to-gitignore/27428/3

The sad thing is I've met René recently and I forgot to ask his opinion on source-based Gradle wrappers.

**Comment by jvz** [comment]
Ah yes, it does look that way. Thanks for the info!
